title: "Kid Icarus: OMM"
description: Contains documentation for all systems, functions and behaviours which have been identified in the game.

url: "https://ordinary-hacker.github.io"
baseurl: "/kid-icarus-omm"

theme: just-the-docs

color_scheme: dark

logo: "assets/images/logo.svg"

callouts:
  warning:
    title: Warning
    color: red
